### ISSUE TITLE
Thank you for this

### ISSUE THREAD

**Issue by BarbzYHOOL** [refringe/CodeIgniter-HTMLPurifier#3]
Thank you, it's working!

**Comment by refringe** [comment]
Happy to help. Be sure to use the latest version of HTML Purifier (4.12.0). The documentation on this project is a little out of date and references an older version.

**Comment by BarbzYHOOL** [comment]
btw why the standalone version?

**Comment by refringe** [comment]
Years ago, when this helper was first written, the standard version of HTML Purifier had you `require` a number of files into your codebase. It just came down to just being easier to use the standalone version. However, it looks like you can now include the standard version with a single line as well. 🤷

I would look into using composer to install HTML Purifier. It allows you to keep track of the HTML Purifier version and update it easily in the future. I plan to update this helper to use the composer version sometime in the future, but I don't know when I'll get around to it.

**Comment by BarbzYHOOL** [comment]
I never use composer, but well I use your method for now

How do I include the standard version with a single line? I might do this and put it in a git submodule or something like that

**Comment by refringe** [comment]
If you don't want to use Composer you can download the standard version into your `third-party` directory and include the 'auto' file:

`require_once '/path/to/htmlpurifier/library/HTMLPurifier.auto.php';`

You can put the `require_once` before [line 22](https://github.com/refringe/CodeIgniter-HTMLPurifier/blob/master/htmlpurifier_helper.php#L22) (the first line within the function).
