### ISSUE TITLE
Some configs has no effect to code.

### ISSUE THREAD

**Issue by Kuzguncukk** [refringe/CodeIgniter-HTMLPurifier#4]
Hi, some configs are not working in my codeigniter project. I installed without composer.

**I added this code in my helper:**

`require_once APPPATH . '/third_party/htmlpurifier/HTMLPurifier.auto.php';`

But when add to HTML.Nofollow, HTML.TargetBlank didn't effect. 

**I solved the problem like this:**

htmlpurifier/AttrTransform/TargetBlank.php line 38:

` if ($scheme->browsable && !$url->isBenign($config, $context)) {`

**I replaced it with this:**

` if ($scheme->browsable && $url->isBenign($config, $context)) {`

It's working now.

**But I couldn't solve some configs:** 

`$config->set('URI.SafeIframeRegexp', '%^(http://|https://|//)(www.youtube.com/embed/|player.vimeo.com/video/|api.soundcloud.com/tracks/)%",');`
`$config->set('HTML.SafeIframe', 'true');`

But it is still deleting iframe code. I think the problem is ''include''. Because it didn't effect what I wanted to change when i changed htmlpurifier/urifilter/SafeIframe.php . Is there anyone who has an idea about this issue?

**Comment by refringe** [comment]
I can try to help you out here but I need to know what your full config and the HTML you're trying to purify looks like.

I would also highly recommend reverting any changes you've made to the HTML Purifier source as this is likely an issue with the config.

**Comment by Kuzguncukk** [comment]
The codes to be cleared come from summernote. (WYSIWYG editor)

When i remove $config->set('HTML.Doctype', 'XHTML 1.0 Strict'); in config block, everything okay. But TargetBlank problem still continues.

**Here is my config code block:**



				case 'summernote':
				$config = \HTMLPurifier_Config::createDefault();
				$config->set('Core.Encoding', $ci->config->item('charset'));
				
				$config->set('HTML.SafeIframe', true); // iframe izin ver
				$config->set('URI.SafeIframeRegexp', '%^(http://|https://|//)(www.youtube.com/embed/|player.vimeo.com/video/|instagram.com/p/|vine.co/v/|www.dailymotion.com/embed/video/|player.youku.com/embed/)%'); //youtube, vimeo, instagram, vine, dailymotion, youku

				$config->set('HTML.Allowed', 'h1,h2,h3,h4,h5,h6,b,strong,u,blockquote[cite],em,code,abbr[title],acronym[title],pre,p[style],a[rel|href|title|target],li,ul,ol,span[style],table[class],tbody,td[abbr],tr,br,iframe[src|height|width|frameborder],div[style],img[src|style]');


				$config->set('Attr.AllowedClasses', 'table, table-bordered');
				$config->set('CSS.AllowedProperties', 'text-align,margin-left,width,font-family');
				$config->set('CSS.AllowedFonts', 'Helvetica,Verdana,Arial,Arial Black,Comic Sans MS,Courier New,Impact,Tahoma,Times New Roman');

				$config->set('HTML.TargetBlank', TRUE); // linklere target blank ekle 
				$config->set('HTML.Nofollow', TRUE); //linklere rel no follow ekle 

				//$config->set('AutoFormat.AutoParagraph', TRUE); // otomatik p tag ile sarmala
				$config->set('AutoFormat.RemoveEmpty', TRUE);	// boş tagleri yoket
				break;

**Comment by refringe** [comment]
I also need an example of input (the HTML before you run it through this function).
